version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"

networks:
  mern-network:
    driver: bridge
